language: node_js
dist: trusty
sudo: required
node_js:
  - '8.9.3'
before_install:
  - export DISPLAY=:99.0
install:
  - sh -e /etc/init.d/xvfb start
  - npm install --ignore-scripts
script:
  - npm test
  - npm run e2e
addons:
  chrome: stable
cache:
  directories:
    - node_modules
notifications:
  email: false
  webhooks:
    on_success: true
    on_failure: true
    on_start: true